name: jupydst
dependencies:
  - jupyter_client=5.3.1=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.4=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - jupyterlab=0.33.11=py36_0
  - jupyterlab_launcher=0.11.2=py36h28b3542_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36h3a684a6_1
  - numpy=1.16.2=py36h926163e_0
  - numpy-base=1.16.2=py36ha711998_0
  - scikit-learn=0.20.3=py36hebd9d1a_0
  - scipy=1.2.1=py36h1a1e112_0
  - seaborn=0.9.0=py36_0
  - pip:
    - astropy==3.1.2
    - beautifulsoup4==4.7.1
    - cdflib==0.3.9
    - heliopy==0.7.0
    - heliosat==0.3.1
    - predstorm==0.1
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.15
    - spacepy==0.2.0
    - sunpy==1.0.1

